### PR TITLE
Fix for js_run_devserver to sync file changes if child process consumes stdin

### PR DESCRIPTION
**Pull request by gregjacobs**
Fixes https://github.com/aspect-build/rules_js/issues/1242

### Type of change

- Bug fix (change which fixes an issue)

**For changes visible to end-users**

- Suggested release notes are provided below: 

The child process of `js_run_devserver` can now consume `stdin` without preventing `js_run_devserver` from syncing upon ibazel's notifications

### Additional info

I'm only alerting the child process of ibazel success after the files have been synced in order to allow the child process to pick up the latest files in the `js_run_devserver` sandbox. This should not be a breaking change because `js_run_devserver` simply doesn't respond to ibazel's success messages currently when the child process adds a 'data' event handler on `process.stdin`.

### Test plan

- Manual testing; please provide instructions so we can reproduce:

Have been trying to think of how this can be tested in an automated fashion, but in the meantime it can be tested manually as follows:

1. Add this snippet to `e2e/js_run_devserver/src/simple.js`:
   ```js
   process.stdin.on('data', chunk => {
       console.log(`Child process's chunk: `, chunk.toString());
   });
   ```

2. Start the dev server:
   ```shell
   cd e2e/js_run_devserver/src
   bazel run :serve_simple
   ```

3. Make file content change in `e2e/js_run_devserver/src/index.html`
4. Observe that `js_run_devserver` sync'd the changed index.html file, and afterwards there's the "Child process's chunk" message on stdout

FYI @gregmagolan

### CODE REVIEW

**Comment by gregmagolan** [comment]
Thanks for the fix and details write up here and in the issue @gregjacobs. Makes sense at first glance. I'll try to fully understand it tomorrow with a fresh brain.

**Comment by gregjacobs** [comment]
@gregmagolan Sounds good. It was definitely a weird one, and took me a few days to track down. I basically had this in my webpack config:

```js
watchOptions: {
    stdin: true,
}
```

which I guess causes Webpack to listen on the `stdin` stream, and seems to prevent `js_run_devserver.mjs` from receiving ibazel's "build success" messages instead.

But did notice that if js_run_devserver's child process has any `process.stdin.on('data', ...)` listener, this also prevents js_run_devserver.mjs from receiving ibazel's messages (except on occasion - catches the messages maybe 10% of the time).

Perhaps this is just a Mac thing though? Haven't tried on other platforms.

**Comment by gregjacobs** [comment]
And there's actually a second part to this, which is that if the child process receives the `"IBAZEL_BUILD_COMPLETED SUCCESS\n"` message before js_run_devserver has synced its files, then an ibazel-aware child process may begin re-bundling with stale files

**Comment by alexeagle** [comment]
Thanks @gregjacobs !!

**Review by alexeagle — APPROVED** [review]

**Pull request merged**
