### PR TITLE
fix: delete .git folder when downloading npm package from git

### PR DESCRIPTION
**Pull request by kormide**
Found that the `.git` folder was non-hermitic in some client work.

### CODE REVIEW

**Comment by gregmagolan-codaio** [comment]
Nice one. Can you add a test to verify that the .git folder is not present in the one package we pull down with git+ssh:
```
"protoc-gen-grpc": "git+ssh://git@github.com:gregmagolan-codaio/protoc-gen-grpc-ts#be5580b06348d3eb9b4610a4a94065154a0df41f",
```

**Comment by kormide** [comment]
Hm, I'm writing a test, but strangely I can't reproduce the `.git` folder existing on my local box. `.gitignore` is present 🤔

**Comment by kormide** [comment]
Oh interesting, generated `repositories.bzl` file strips the transforms the `git+ssh` url into `https://codeload.github.com/...`. So by the time the git+ssh check occurs in npm_import, it doesn't go through this logic.

**Comment by gregmagolan** [comment]
Hmm. You might need to switch the repo it pulls. I swear that one took the right code path when I landed it 🤨

**Comment by kormide** [comment]
So from what I can tell, `pnpm` will take a `git+ssh` dependency and automatically convert it into a tarball url resolution in `pnpm-lock.yaml`. I think I can only replicate this case with a private repository.

It should be easier to replicate this case for a test using an `npm_import`.

**Comment by gregmagolan** [comment]
Testing with npm import sgtm

**Comment by kormide** [comment]
Updated

**Pull request closed without merging**
