### PR TITLE
Update the npm_import documentation to have the correct self-reference.

### PR DESCRIPTION
**Pull request by kylepl**
See the reference just above, it has one less underscore.

---

### Type of change

- Documentation (updates to documentation or READMEs)

### CODE REVIEW

**Comment by jbedard** [comment]
I believe it's actually the opposite and it should be two. Want to update the one above to two?

**Comment by kylepl** [comment]
Done.

**Comment by jbedard** [comment]
@kylepl looks like that file is generated and you need to change it at the source, see npm/private/npm_import.bzl

**Comment by kylepl** [comment]
Hm, it seems like the source actually has `npm__at_types_node__15` (i.e. double underscores twice). So I'm not sure why this does not match then. If there are steps that generate it, it's likely more involved then I'm willing to patch.

**Comment by jbedard** [comment]
I think I see the bad one in the bzl file, there's also a few that correctly have the double underscore so you might just be looking at the wrong one?

If it's too much work I can try but it would be great if you could give it another shot since you have this going already 👍

**Pull request closed without merging**
