### PR TITLE
test: add npm_package(root_paths) test

### PR DESCRIPTION
**Pull request by jbedard**
This is an attempt at reproducing https://github.com/aspect-build/rules_js/issues/471. It's possible there is no bug but I think we need some `npm_package(root_paths)` tests anyway?

Maybe don't merge until that bug is resolved, maybe this will change to actually reproduce the issue...

### CODE REVIEW

**Comment by cgrindel** [comment]
@gregmagolan When you get a chance, can you give this PR a review?

**Comment by gregmagolan** [comment]
Looks the issue is closed by the reporter: https://github.com/aspect-build/rules_js/issues/471#issuecomment-1270110589

**Review by gregmagolan — APPROVED** [review]
🌮

**Comment by jbedard** [comment]
Yeah it didn't seem to be a rules_js issue but I thought my attempt at reproducing it was a reasonable test to add.

**Pull request merged**
