### PR TITLE
build: use Aspect CLI in e2e tests

### PR DESCRIPTION
**Pull request by gregmagolan**
Except for js_run_devserver which seems to be failing on CI in a way that I can't repro locally. 

https://github.com/aspect-build/rules_js/actions/runs/3463927116/jobs/5784823402

### CODE REVIEW

**Review by kormide — APPROVED** [review]

**Review by jbedard — APPROVED** [review]

**Comment by jbedard** [comment]
For the changed test... are you seeing something such as https://github.com/aspect-build/rules_js/pull/601 ?

**Comment by gregmagolan** [comment]
> For the changed test... are you seeing something such as #601 ?

It seems to be timing out on the "added a new file to a target in BUILD file" test case on CI but I can't repro locally 🤷

**Comment by jbedard** [comment]
That's a different error then what that PR was fixing. I had one other error while doing that PR that I didn't fix though, I don't recall the details though.

**Comment by gregmagolan** [comment]
Those js_run_devserver tests just seem flaky in general and too dependent on timing. They could still use some work but having flaky ones is still better than not having any coverage for that rule.

**Comment by jbedard** [comment]
Yeah I don't think we shouldn't disable them, that would be worse imo, but it does seem like they need some work to see why they are so flaky.

I was able to reproduce the port one locally but clearly there's more.

**Pull request merged**
