### PR TITLE
fix: fix relative paths of bins in lifecycle hooks for @scoped packages

### PR DESCRIPTION
**Pull request by jfirebaugh**
We have forked [nodegit](https://www.npmjs.com/package/nodegit) in order to provide precompiled binaries for Node 16 and arm64, which aren't yet supported upstream. Our forked package is published as `@figma/nodegit` and we were using it successfully with vanilla npm and with rules_nodejs. However, I can't get it to install via rules_js.

I think this is probably a bug in rules_js's implementation of lifecycle scripts, but correct me if I'm wrong.

```
$ bazel build //examples/nodegit:node_modules     
INFO: Analyzed target //examples/nodegit:node_modules (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/john/figma/rules_js/BUILD.bazel:10:22: Running lifecycle hooks on npm package @figma/nodegit@0.28.0-figma.2 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/npm/private/lifecycle/lifecycle-hooks.sh @figma/nodegit ../../../external/npm__at_figma_nodegit__0.28.0-figma.2/package ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/private/var/tmp/_bazel_john/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/2/execroot/aspect_rules_js/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@figma+nodegit@0.28.0-figma.2/node_modules/@figma/node-pre-gyp/bin/node-pre-gyp'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
Error: @figma/nodegit@0.28.0-figma.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
Exit status 1
    at EventEmitter.<anonymous> (/private/var/tmp/_bazel_john/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/2/execroot/aspect_rules_js/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/npm/private/lifecycle/lifecycle-hooks.sh.runfiles/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:73342)
    at EventEmitter.emit (node:events:394:28)
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_john/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/2/execroot/aspect_rules_js/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/npm/private/lifecycle/lifecycle-hooks.sh.runfiles/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:79804)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  errno: 1,
  code: 'ELIFECYCLE',
  pkgid: '@figma/nodegit@0.28.0-figma.2',
  stage: 'install',
  script: 'node lifecycleScripts/preinstall && node lifecycleScripts/install',
  pkgname: '@figma/nodegit'
}

> @figma/nodegit@0.28.0-figma.2 install /private/var/tmp/_bazel_john/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/2/execroot/aspect_rules_js/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@figma+nodegit@0.28.0-figma.2/node_modules/@figma/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
Target //examples/nodegit:node_modules failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.769s, Critical Path: 5.42s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

### CODE REVIEW

**Comment by gregmagolan** [comment]
Hmm. Its failing looking for `@figma/node-pre-gyp/bin/node-pre-gyp`. is `@figma/node-pre-gyp` a dependency of `@figma/nodegit`?

**Comment by jfirebaugh** [comment]
There's no package named `@figma/node-pre-gyp`. The package has a [dependency on `node-pre-gyp`](https://github.com/figma/nodegit/blob/a317471865cab7a4f1a75add10d5dc7348b536ab/package.json#L47), without an npm namespace.

**Comment by gregmagolan** [comment]
Oh. Interesting. I wonder how where the source of this path is then?
```
@figma+nodegit@0.28.0-figma.2/node_modules/@figma/node-pre-gyp/bin/node-pre-gyp
```

**Comment by jfirebaugh** [comment]
The install script [spawns `node-pre-gyp`](https://github.com/figma/nodegit/blob/193c628845c205406d0e1b96117384abbef66ac3/lifecycleScripts/install.js#L32), and I assume that resolves to the bin generated by rules_js:

https://github.com/aspect-build/rules_js/blob/03207bbce86b765d28a105618bff6fdcaa386c72/npm/private/lifecycle/lifecycle-hooks.js#L49-L50

Is that relative path wrong if the package whose lifecycle hooks are being executed is a scoped package?

**Comment by jfirebaugh** [comment]
Yeah, that's the bug. See above commit for my fix.

**Comment by gregmagolan** [comment]
Nice find. Thanks for the fix!

**Review by gregmagolan — APPROVED** [review]
🌮

**Pull request merged**
