### PR TITLE
fix: `stamped_package_json` following bazel-lib update to 2.0.x

### PR DESCRIPTION
**Pull request by supercairos**
Fix this issue: #1373

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
Hm, this will be broken if you are still on Bazel-lib 1.x though. We should try to find a solution that can work with both.

**Comment by supercairos** [comment]
How can we check the version of `bazel-lib` ?

We could do this if `bazel-lib.major > 2`

**Comment by kormide** [comment]
> How can we check the version of `bazel-lib` ?
> 
> We could do this if `bazel-lib.major > 2`

I have a fix of this sort going in https://github.com/aspect-build/rules_js/pull/1376. I'll cut a release once it lands.

**Comment by kormide** [comment]
Closing as this is fixed in v1.34.1.

**Pull request closed without merging**
