### PR TITLE
Shebang bug fix in launcher script

### PR DESCRIPTION
**Pull request by jgao54**
Cannot have newline before shebang.
### Type of change
- Bug fix

### Test plan
- Manual testing: before this change, an image that uses this `js_image_layer` was still getting `exec format error` when trying to execute the js binary, which is expected since shebang cannot have newline in front of it. Error is fixed with this change.
- Updated unit & e2e tests.

### CODE REVIEW

**Comment by jbedard** [comment]
@thesayyn do you know any way to test this?

**Review by jbedard — APPROVED** [review]

**Comment by thesayyn** [comment]
can be added here https://github.com/aspect-build/rules_js/blob/bde738920fcd37695ca82365009d48474b0cf99f/e2e/js_image_oci/src/test.yaml#L4-L17 instead of invoking it via bash, script can be invoked directly to see if it works directly.

something like 

```
- name: 'smoke'
   entrypoint: /app/src/main
```

**Review by thesayyn — APPROVED** [review]
LGTM

**Comment by jgao54** [comment]
I'm seeing: `line 9: field entrypoint not found in type v2.CommandTest` errors, going to undo the e2e test change for now.

**Comment by jgao54** [comment]
@thesayyn  will need another approval, thanks!

**Comment by thesayyn** [comment]
> I'm seeing: `line 9: field entrypoint not found in type v2.CommandTest` errors, going to undo the e2e test change for now.

sorry it's supposed to be `command`.

**Comment by jgao54** [comment]
@thesayyn updated again.

**Comment by jgao54** [comment]
The e2e failures look unrelated to my change now.

**Review by alexeagle — APPROVED** [review]

**Pull request merged**
