### PR TITLE
chore: remove expand_template in exchange for bazel-lib

### PR DESCRIPTION
**Pull request by thesayyn**
### Type of change

- Refactor (a code change that neither fixes a bug or adds a new feature)

### CODE REVIEW

**Review by gregmagolan — CHANGES_REQUESTED** [review]
Holding on this for now to give users notice & time to flip downstream usages.

**Comment by alexeagle** [comment]
Not a breaking change, and I vote we land this now. But added to the 2.0 milestone anyway so we don't lose track.

**Comment by jbedard** [comment]
@thesayyn want to finish this? I don't think it's breaking like Alex said so I think we should land it or close this...

**Comment by gregmagolan** [comment]
Closing in favor of https://github.com/aspect-build/rules_js/pull/1557

**Pull request closed without merging**
