### PR TITLE
feat(update_pnpm_lock): provide a utility that helps keep your data u…

### PR DESCRIPTION
**Pull request by alexeagle**
…pdated with all package.json files

If we like this approach, I'll update docs to suggest users run it.

### CODE REVIEW

**Comment by alexeagle** [comment]
Demo:
```
~/Projects/rules_js$ bazel run @aspect_rules_js//npm:update_translate_lock_data 
INFO: Analyzed target //npm:update_translate_lock_data (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //npm:update_translate_lock_data up-to-date:
  bazel-bin/npm/update_translate_lock_data
INFO: Elapsed time: 0.078s, Critical Path: 0.00s
INFO: 2 processes: 2 internal.
INFO: Running command line: bazel-bin/npm/update_translate_lock_data
INFO: Build completed successfully, 2 total actions
Finding packages in the pnpm workspace rooted at /home/alexeagle/Projects/rules_js
Paste this snippet into your 'npm_translate_lock()':
    data = [
        "//:package.json",
        "//examples/js_binary:package.json",
        "//examples/macro:package.json",
        "//examples/npm_deps:package.json",
        "//examples/npm_package/libs/lib_a:package.json",
        "//examples/npm_package/packages/pkg_a:package.json",
        "//examples/npm_package/packages/pkg_b:package.json",
        "//examples/webpack_cli:package.json",
        "//js/private/coverage/bundle:package.json",
        "//npm/private/test:package.json",
    ]
```

**Comment by alexeagle** [comment]
Note, I added a doc about running the npm recursive ls - so this is low priority.

**Comment by gregmagolan** [comment]
Converting to DRAFT to keep the bots from pinging for reviews while this is on the back burner

**Comment by Toxaris** [comment]
Would it be possible and make sense to support reading the lists of package.json files from a file, and then offer a sh_binary that updates that file in the source tree? That would avoid the manual "paste this snippet" step.

**Comment by alexeagle** [comment]
sure, but I'm not sure that's necessarily better. We just added a feature in rules_oci that similarly wants to vendor some data into the WORKSPACE file, I think we just want to print a buildozer command to make it a bit easier.

**Comment by jbedard** [comment]
@alexeagle this is old and untouched so I'm closing for now...

**Pull request closed without merging**
