### PR TITLE
build: bump @kubernetes/client-node dep due to failure

### PR DESCRIPTION
**Pull request by gregmagolan**
Not sure why but at some point the following error started to happen outside of bazel in the prepare lifecycle hook which is being testing:
```
src/oidc_auth.ts(2,48): error TS2307: Cannot find module 'openid-client' or its corresponding type declarations.
```

full error log:
```
...2107_38676d339eae84ca91c8293d2287683a npm-install$ npm install
│ npm WARN deprecated har-validator@5.1.5: this library is no longer supported
│ npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
│ npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.
│ npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8/
│ npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
│ > @kubernetes/client-node@0.18.0 prepare
│ > npm run build
│ > @kubernetes/client-node@0.18.0 build
│ > tsc
│ src/oidc_auth.ts(2,48): error TS2307: Cannot find module 'openid-client' or its corresponding type declarations.
│ npm ERR! code 2
│ npm ERR! path /Users/greg/Library/pnpm/store/v3/tmp/_tmp_92107_38676d339eae84ca91c8293d2287683a
│ npm ERR! command failed
│ npm ERR! command sh -c -- npm run build
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     /Users/greg/.npm/_logs/2023-01-13T23_24_58_155Z-debug-0.log
└─ Failed in 12s at /Users/greg/Library/pnpm/store/v3/tmp/_tmp_92107_38676d339eae84ca91c8293d2287683a
 ERR_PNPM_PREPARE_PACKAGE  Failed to prepare git-hosted package fetched from "https://codeload.github.com/kubernetes-client/javascript/tar.gz/763decf": @kubernetes/client-node@0.18.0 npm-install: `npm install`
Exit status 2
```

This PR the problematic dep to the latest commit hash which doesn't have this issue

### CODE REVIEW

**Review by jbedard — APPROVED** [review]

**Comment by jbedard** [comment]
I was getting the same error but assumed it was a local problem since CI was green.

**Comment by gregmagolan** [comment]
Whoops. There was still a broken diff test. How did this get auto-merged?

**Comment by gregmagolan** [comment]
Will put up a follow-up PR

**Comment by jbedard** [comment]
> Whoops. There was still a broken diff test. How did this get auto-merged?

I also had something auto-merge earlier before CI finished. I pressed the auto-merge button and then it merged instantly. I assumed I had pressed the wrong button or something. But it happened to you as well now?

**Comment by gregmagolan** [comment]
Unless I'm crazy I don't recall pressing merge. Tho I don't recall pressing auto-merge either.

**Comment by jbedard** [comment]
This page says you enabled it, then I saw it merge instantly when I approved it.

**Pull request merged**
