### PR TITLE
test: add e2e test containing transitive npm_package deps

### PR DESCRIPTION
**Pull request by jbedard**
This adds an extra indirect dependency to the `npm_link_package` test to ensure indirect deps are passed along to runtime.

The second commit adds an esm version of that test. Basically copy and pasted and switched to esm which requires some extra node flags and minor other differences. Currently the file structure and files are very similar so a visual diff between the two nicely shows the differences.

### CODE REVIEW

**Comment by alexeagle** [comment]
Hey do you still want to finish this one?

**Comment by jbedard** [comment]
Now that we have Greg's changes I'll give it a shot 👍

**Comment by jbedard** [comment]
@gregmagolan this is passing now and ready

**Review by gregmagolan — APPROVED** [review]
🌮

**Pull request merged**
